monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - cvDownloaded
        - movie
        - errors
        - opinion

    handlers:
        slack_cv_handler:
            type: slackWebhook
            webhook_url: '%env(SLACK_CV_DOWNLOADED)%'
            channel: '%env(SLACK_CV_DOWNLOADED)%'
            bot_name: 'CV'
            icon_emoji: ':ghost:'
            level: debug
            channels: [ cvDownloaded ]
            include_extra: true
        slack_movie_handler:
            type: slackWebhook
            webhook_url: '%env(SLACK_MOVIE)%'
            channel: '%env(SLACK_MOVIE)%'
            bot_name: 'CV'
            icon_emoji: ':ghost:'
            level: debug
            channels: [ movie ]
            include_extra: true
        slack_errors_handler:
            type: slackWebhook
            webhook_url: '%env(SLACK_ERRORS)%'
            channel: '%env(SLACK_ERRORS)%'
            bot_name: 'CV'
            icon_emoji: ':ghost:'
            level: debug
            channels: [ errors ]
            include_extra: true
        slack_opinion_handler:
            type: slackWebhook
            webhook_url: '%env(SLACK_OPINION)%'
            channel: '%env(SLACK_OPINION)%'
            bot_name: 'CV'
            icon_emoji: ':ghost:'
            level: debug
            channels: [ opinion ]
            include_extra: true

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: [ "!event" ]
#            main:
#                type: fingers_crossed
#                action_level: error
#                handler: nested
##                excluded_http_codes: [404, 405]
#                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
