web:
  container_name: mmiklaszewski_web
  build: .
  ports:
    - "20185:80"
  volumes:
    - .:/var/www/html
db:
  container_name: mmiklaszewski_db
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: pass
    MYSQL_DATABASE: app
    MYSQL_USER: dev
    MYSQL_PASSWORD: "SsGR9%H46J"
  ports:
    - "3081:3306"
phpmyadmin:
  container_name: mmiklaszewski_phpmyadmin
  image: phpmyadmin/phpmyadmin
  ports:
    - '30185:80'
  environment:
    PMA_HOSTS: db
    MYSQL_ROOT_PASSWORD: pass
  links:
    - db