parameters:
    app.supported_locales: 'pl|en'


services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $serperToken: '%env(SERPER_TOKEN)%'
            $openAiToken: '%env(OPEN_AI_TOKEN)%'
            $slackCVLogger: '@monolog.logger.cvDownloaded'
            $slackMovieLogger: '@monolog.logger.movie'
#            $slackErrors: '@monolog.logger.errors'
            $slackOpinionLogger: '@monolog.logger.opinion'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Infrastructure/Entity/'
            - '../src/Kernel.php'


