parameters:
    app.supported_locales: 'pl|en'


services:

    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $serperToken: '%env(SERPER_TOKEN)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'


